/** Text files generated from refinement state: the product owner's briefing, proposal.md, and one file per approved item. */
import * as path from "node:path";
import { z } from "zod";
import { EXAMPLES } from "../schema/examples";
import { RefineOutput } from "../schema/outputs";
import {
  type RefinementItem,
  type RefinementRevision,
  type RefinementRun,
  type RefinementState,
  RefinementStatus,
} from "../schema/refinement";
import { slugify } from "../util/fsx";
import { readRoleNotes } from "./briefing";
import { type Ctx, rel } from "./project";
import type { PlannedWork } from "./refinementContext";
import { refinementPaths, type RefinementRef } from "./refinementStore";

const listOrNone = (values: string[]) => (values.length ? values.join(", ") : "none");

/** One row per item: the compact view used in the briefing and in proposal.md. */
function itemsTable(revision: RefinementRevision): string[] {
  return [
    "| Item | Title | Depends on | Mode | Criteria | Prerequisite |",
    "|---|---|---|---|---|---|",
    ...revision.items.map(
      (item) =>
        `| ${item.id} | ${item.title} | ${listOrNone(item.dependsOn)} | ${item.suggestedMode} | ${item.acceptanceCriteria.length} | ${item.prerequisiteFor ? "yes" : ""} |`,
    ),
  ];
}

function itemDetails(item: RefinementItem): string[] {
  const out = [
    `### ${item.id} · ${item.title}`,
    "",
    `**Goal:** ${item.goal}`,
    "",
    "**Scope:**",
    ...item.scope.map((entry) => `- ${entry}`),
    "",
    "**Acceptance criteria (draft):**",
    ...item.acceptanceCriteria.map((criterion) => `- ${criterion}`),
    "",
    `**Depends on:** ${listOrNone(item.dependsOn)}`,
  ];
  if (item.prerequisiteFor) out.push(`**Prerequisite for:** ${item.prerequisiteFor}`);
  out.push(`**Suggested mode:** ${item.suggestedMode} — ${item.modeReason}`);
  if (item.touches.length) out.push(`**Likely affected:** ${item.touches.join(", ")}`);
  if (item.risks.length) out.push(`**Risks:** ${item.risks.join("; ")}`);
  return out;
}

/** proposal.md: the latest revision, for the user to review. */
export function renderProposal(s: RefinementState, revision: RefinementRevision): string {
  const out: string[] = [
    `# Refinement · ${s.title}`,
    "",
    `Refinement: ${s.id} · revision ${revision.revision} · ${revision.at}`,
    "",
    "<!-- Generated by aw from the product owner's proposal. Ask for changes with `aw refine note` instead of editing this file. -->",
    "",
    "## Summary",
    revision.summary,
    "",
    "## Items",
    ...itemsTable(revision),
  ];
  for (const item of revision.items) out.push("", ...itemDetails(item));
  out.push("", "## Coverage of the slice description", ...revision.coverage.map((entry) => `- ${entry.requirement} → ${entry.items.join(", ")}`));
  if (revision.outOfScope.length) out.push("", "## Out of scope", ...revision.outOfScope.map((entry) => `- ${entry}`));
  if (revision.openQuestions.length) out.push("", "## Open questions", ...revision.openQuestions.map((entry) => `- ${entry}`));
  if (revision.addressedNotes.length) {
    out.push("", "## Answers to the user's notes", ...revision.addressedNotes.map((answer) => `- ${answer.noteId}: ${answer.note}`));
  }
  return `${out.join("\n")}\n`;
}

/** briefing.md: everything the product owner needs for one run. */
/** What the product owner gets besides the slice: see refinementContext.ts. */
export interface RefinementContext {
  /** refine.contextDocs files, read in full before splitting. */
  documentation: string[];
  work: PlannedWork;
}

/** Where another refinement stands, in words for the briefing. */
function refinementProgress(s: RefinementState): string {
  switch (s.status) {
    case RefinementStatus.enum.APPROVED:
      return "approved; its items are tasks to deliver";
    case RefinementStatus.enum.PROPOSED:
      return "proposed, waiting for the user's approval";
    case RefinementStatus.enum.WORKING:
      return "being split right now";
    default:
      return s.revisions.length ? "being revised" : "not split yet";
  }
}

/** Items of another refinement: the approved revision, or the latest proposal. */
function shownRevision(s: RefinementState): RefinementRevision | undefined {
  if (s.status === RefinementStatus.enum.APPROVED) return s.revisions.find((revision) => revision.revision === s.approvedRevision);
  return s.revisions.at(-1);
}

/** Titles and paths only: the product owner reads the details itself when it needs them. */
function plannedWorkSection(ctx: Ctx, work: PlannedWork): string[] {
  const out = [
    "",
    "## Work already planned or done",
    "Don't plan it again. Build on it, and keep this slice's items from overlapping it.",
    "",
  ];
  for (const { ref, state } of work.refinements) {
    out.push(`- Refinement ${state.id} · ${state.title} · ${refinementProgress(state)}`);
    const approved = state.status === RefinementStatus.enum.APPROVED;
    for (const item of shownRevision(state)?.items ?? []) {
      const file = rel(ctx, path.join(refinementPaths(ref).items, itemFileName(item)));
      out.push(`  - ${item.id} ${item.title}${approved ? ` (${file})` : ""}`);
    }
  }
  if (work.activeTask) out.push(`- Task ${work.activeTask.id} · ${work.activeTask.title} · ${work.activeTask.status} (in progress)`);
  for (const task of work.archivedTasks) out.push(`- Task ${task.id} · ${task.title} · ${task.status} (archived)`);
  if (out.length === 4) out.push("Nothing yet: this is the first slice.");
  return out;
}

export function renderRefinementBriefing(
  ctx: Ctx,
  s: RefinementState,
  ref: RefinementRef,
  run: RefinementRun,
  context: RefinementContext,
): string {
  const paths = refinementPaths(ref);
  const previous = s.revisions.at(-1);
  const out: string[] = [
    `# Briefing · product owner · refinement ${s.id}`,
    "",
    `Refinement: ${s.id} · ${s.title} · run ${run.id} · this will be revision ${s.revisions.length + 1}`,
    `Write all free-text fields in: ${ctx.config.language}.`,
    "",
    "## Your job",
    "Split the slice described in the input file into small, vertical, independently deliverable tasks. Each task will later go through the aw pipeline on its own, planned in detail by the scrum-master.",
    "",
    '1. Read ALL the files under "Project documentation" below: the product, its domains, the planned slices.',
    `2. Read the slice: ${rel(ctx, paths.input)}`,
    "3. Explore what you need in the repository with Read, Grep and Glob: the modules the slice touches, the test layout.",
    `4. Write your proposal as JSON to ${rel(ctx, paths.proposal)} with the Write tool. It is the only file you may write.`,
    "5. Run `aw refine submit`. If it reports errors, fix the file and run it again.",
    `6. Reply with ONE line, e.g. "product-owner ${run.id}: proposed 4 items".`,
    "",
    "## Limits",
    `- At most ${ctx.config.refine.maxCriteriaPerItem} acceptance criteria per item: split bigger items.`,
    `- At most ${ctx.config.refine.maxItems} items: for a bigger slice, propose in \`summary\` how to split it into smaller slices.`,
  ];

  const notes = s.notes.filter((note) => run.consumedNotes.includes(note.id));
  if (notes.length) {
    out.push("", "## Must address (each needs an entry in addressedNotes)", ...notes.map((note) => `- ${note.id}: ${note.text}`));
  }
  if (previous) {
    out.push(
      "",
      `## Previous proposal (revision ${previous.revision}) — the user asked for changes`,
      ...itemsTable(previous),
      "",
      `Full text: ${rel(ctx, paths.proposalView)}. Keep the items the notes don't touch unchanged: same titles and order.`,
    );
  }
  out.push(
    "",
    "## Project documentation (read all of it before splitting)",
    ...context.documentation.map((file) => `- ${file}`),
    ...plannedWorkSection(ctx, context.work),
  );
  if (ctx.config.docs.length) {
    out.push("", "## Other documentation (read when relevant)", ...ctx.config.docs.map((doc) => `- ${doc.path} — ${doc.when}`));
  }
  out.push("", "Project instructions (CLAUDE.md) are already in your context.");
  const repositoryNotes = readRoleNotes(ctx, "product-owner");
  if (repositoryNotes) out.push("", "## Repository notes for the product owner", repositoryNotes);

  const schema = z.toJSONSchema(RefineOutput, { io: "input", unrepresentable: "any" });
  out.push(
    "",
    "## Output format (`aw schema refine` prints the same)",
    "Fields with defaults may be omitted; unknown fields are rejected.",
    "",
    "```json",
    JSON.stringify(schema, null, 2),
    "```",
    "",
    "Example:",
    "",
    "```json",
    JSON.stringify(EXAMPLES.refine, null, 2),
    "```",
  );
  return `${out.join("\n")}\n`;
}

/** File name of an approved item, e.g. "02-create-a-user.md": sorts in delivery order. */
export function itemFileName(item: RefinementItem): string {
  return `${String(item.position).padStart(2, "0")}-${slugify(item.title)}.md`;
}

/** One approved item as a task description for `/aw:scrum-master <file>`; it becomes the task's requirements.md. */
export function renderItem(s: RefinementState, revision: RefinementRevision, item: RefinementItem): string {
  const titleOf = new Map(revision.items.map((other) => [other.id, other.title]));
  const dependencies = item.dependsOn.map((id) => `${id} ${titleOf.get(id) ?? ""}`.trim());
  const out = [
    `<!-- aw: refinement ${s.id}, item ${item.id} (${item.position} of ${revision.items.length}) -->`,
    `# ${item.title}`,
    "",
    `**Goal:** ${item.goal}`,
    "",
    "**Scope:**",
    ...item.scope.map((entry) => `- ${entry}`),
    "",
    "**Acceptance criteria (draft, refine them in the plan):**",
    ...item.acceptanceCriteria.map((criterion) => `- ${criterion}`),
    "",
    `**Depends on:** ${dependencies.length ? dependencies.join("; ") : "none"}`,
  ];
  if (item.prerequisiteFor) out.push(`**Prerequisite for:** ${item.prerequisiteFor}`);
  out.push(`**Suggested mode:** ${item.suggestedMode} — ${item.modeReason}`);
  if (item.touches.length) out.push(`**Likely affected:** ${item.touches.join(", ")}`);
  if (item.risks.length) out.push(`**Risks:** ${item.risks.join("; ")}`);

  out.push(
    "",
    "## Context: the whole slice",
    revision.summary,
    "",
    ...revision.items.map((other) =>
      other.id === item.id ? `${other.position}. **${other.id} ${other.title}** ← this task` : `${other.position}. ${other.id} ${other.title}`,
    ),
  );
  const fromDescription = revision.coverage.filter((entry) => entry.items.includes(item.id));
  if (fromDescription.length) {
    out.push("", "## From the slice description", ...fromDescription.map((entry) => `> ${entry.requirement}`));
  }
  return `${out.join("\n")}\n`;
}
