/** Human-readable views generated from state: plan.md (for approval) and report.md (for the archive). */
import type { PlanRevision, Run, TaskState } from "../schema/state";
import { Role } from "../schema/status";
import { describeGate } from "./gates";
import { describeFinding, submittedRuns } from "./machine";

export function renderPlan(s: TaskState, plan: PlanRevision): string {
  const out: string[] = [
    `# Plan · ${s.title}`,
    "",
    `Task: ${s.id} · revision ${plan.revision} · mode: ${plan.mode} · ${plan.createdAt}`,
    "",
    "<!-- Generated by aw from the plan JSON. Edit the JSON and run `aw sm plan` again instead of editing this file. -->",
    "",
    "## Summary",
    plan.summary,
    "",
    "## Acceptance criteria",
    ...plan.acceptanceCriteria.map((a) => `- **${a.id}** ${a.text}`),
  ];
  if (plan.contract.trim()) out.push("", "## Contract", plan.contract.trim());
  out.push("", "## Approach", ...plan.approach.map((step, i) => `${i + 1}. ${step}`));
  if (plan.testStrategy.trim()) out.push("", "## Test strategy", plan.testStrategy.trim());
  if (plan.relevantDocs.length) out.push("", "## Relevant docs", ...plan.relevantDocs.map((d) => `- \`${d.path}\` — ${d.why}`));
  if (plan.outOfScope.length) out.push("", "## Out of scope", ...plan.outOfScope.map((x) => `- ${x}`));
  if (plan.risks.length) out.push("", "## Risks", ...plan.risks.map((x) => `- ${x}`));
  return `${out.join("\n")}\n`;
}

const minutes = (a?: string, b?: string) =>
  a && b ? `${Math.max(0, Math.round((Date.parse(b) - Date.parse(a)) / 60000))} min` : "—";

function runHeadline(r: Run): string {
  const what = r.role === Role.enum.reviewer ? `reviewer (${r.target})` : r.role;
  const verdict = r.role === Role.enum.reviewer && r.output ? ` · ${r.output.verdict}` : "";
  const rejects = r.submitAttempts.filter((a) => !a.ok).length;
  const testSeconds = Math.round(r.testRuns.reduce((sum, t) => sum + t.durationMs, 0) / 1000);
  return `### ${r.id} · ${what} · iteration ${r.iteration} · ${r.state}${verdict} · ${minutes(r.startedAt, r.finishedAt)}${
    rejects ? ` · ${rejects} rejected submit(s)` : ""
  }${r.testRuns.length ? ` · ${r.testRuns.length} test run(s), ${testSeconds}s` : ""}`;
}

function renderRun(r: Run, out: string[]): void {
  out.push("", runHeadline(r));
  if (r.failReason) out.push(`Failed: ${r.failReason}`);
  if (r.stoppedWithoutSubmit) out.push("Agent stopped without submitting.");
  if (r.transcriptPath) out.push(`Transcript: \`${r.transcriptPath}\``);
  const o = r.output;
  if (!o) return;
  out.push("", o.summary);
  if (r.role === Role.enum.tester && r.output) {
    for (const t of r.output.tests) out.push(`- ${t.id} [${t.kind}${t.edgeCase ? ", edge" : ""}; ${t.covers.join(", ")}] \`${t.file}\` — ${t.title}`);
    for (const u of r.output.untestedCriteria) out.push(`- Untested: ${u.ac} — ${u.reason}`);
  }
  if (r.role === Role.enum.reviewer && r.output) {
    for (const f of r.output.findings) out.push(`- ${describeFinding(f)}`);
    for (const p of r.output.previousFindings) out.push(`- ${p.id}: ${p.status}${p.note ? ` — ${p.note}` : ""}`);
    const cov = r.output.acCoverage.map((c) => `${c.ac} ${c.verdict}`).join(", ");
    if (cov) out.push(`- Coverage: ${cov}`);
  }
  if (r.role === Role.enum.coder && r.output) {
    for (const f of r.output.filesChanged) out.push(`- ${f.change} \`${f.path}\` — ${f.why}`);
    for (const d of r.output.decisions) out.push(`- Decision: ${d.decision} — ${d.rationale}`);
    for (const d of r.output.deviationsFromPlan) out.push(`- Deviation: ${d.what} — ${d.why}`);
    for (const d of r.output.testDisputes) out.push(`- Dispute ${d.testId}: ${d.reason}`);
    for (const d of r.output.docsUpdated) out.push(`- Docs: \`${d.path}\` — ${d.what}`);
  }
  for (const g of r.gates) out.push(`- Gate ${describeGate(g)}`);
  for (const w of r.warnings) out.push(`- Warning: ${w}`);
  for (const q of o.openQuestions) out.push(`- Open question: ${q}`);
  for (const n of o.processNotes) out.push(`- Process note: ${n}`);
}

export function renderReport(s: TaskState): string {
  const plan = s.plans.find((p) => p.revision === s.approvedPlanRevision) ?? s.plans.at(-1);
  const count = (role: Role) => submittedRuns(s, role).length;
  const iterations = `tests ${count(Role.enum.tester)}, code ${count(Role.enum.coder)}`;
  const out: string[] = [
    `# ${s.id} · ${s.title}`,
    "",
    `- Status: **${s.status}** · mode: ${s.mode} · source: ${s.source.kind}${s.source.ref ? ` (${s.source.ref})` : ""}`,
    `- Created: ${s.createdAt} · finished: ${s.acceptedAt ?? s.updatedAt} · duration: ${minutes(s.createdAt, s.acceptedAt ?? s.updatedAt)}`,
    `- Iterations: ${iterations} · plan revisions: ${s.plans.length} · runs: ${s.runs.length}`,
  ];
  if (plan) {
    out.push("", "## Plan (approved revision)", plan.summary, "", ...plan.acceptanceCriteria.map((a) => `- **${a.id}** ${a.text}`));
  }
  out.push("", "## Runs");
  for (const r of s.runs) renderRun(r, out);
  if (s.docsChecks.length) {
    out.push("", "## Documentation checks");
    for (const d of s.docsChecks) {
      out.push(`- ${d.at} · ${d.verdict}`, ...d.items.map((i) => `  - \`${i.path}\`: ${i.status} — ${i.note}`));
    }
  }
  const followUps = s.runs.flatMap((r) => (r.role === Role.enum.reviewer && r.output ? r.output.followUps : []));
  if (followUps.length) out.push("", "## Follow-ups", ...followUps.map((f) => `- ${f.text}`));
  if (s.retro) {
    out.push("", "## Retro");
    s.retro.wentWell.forEach((x) => out.push(`- 👍 ${x}`));
    s.retro.wentWrong.forEach((x) => out.push(`- 👎 ${x}`));
    s.retro.processImprovements.forEach((x) => out.push(`- 🔧 ${x}`));
    if (s.retro.notes) out.push("", s.retro.notes);
  }
  out.push("", "## Timeline");
  for (const e of s.history) {
    out.push(
      e.type === "transition"
        ? `- ${e.at} · ${e.by} · ${e.from} → ${e.to}${e.note ? ` — ${e.note}` : ""}`
        : `- ${e.at} · ${e.by} · ${e.event}${e.runId ? ` (${e.runId})` : ""}${e.note ? ` — ${e.note}` : ""}`,
    );
  }
  return `${out.join("\n")}\n`;
}
