// Bundles the aw CLI (src/) with its dependencies into a single file inside the plugin,
// so repositories using the plugin need no npm install.
import { build } from "esbuild";

await build({
  entryPoints: ["src/cli.ts"],
  outfile: "plugins/aw/cli/aw.mjs",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  legalComments: "none",
  banner: {
    js: [
      "#!/usr/bin/env node",
      "// GENERATED by scripts/build.mjs from src/ — do not edit by hand.",
      "import { createRequire as __awCreateRequire } from 'node:module';",
      "const require = __awCreateRequire(import.meta.url);",
    ].join("\n"),
  },
});
console.log("built plugins/aw/cli/aw.mjs");
